name: CI for Express App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 🧾 Checkout code
      uses: actions/checkout@v3

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.14.0'  # Match your local version

    - name: 📦 Install dependencies
      run: npm install

    - name: ✅ Run tests (or dummy step)
      run: npm test

    - name: 🚀 Simulated deploy
      run: echo "Deploy complete (simulation)"
